# Generated by Django 6.0.7 on 2026-08-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name_sanskrit', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('name_hindi', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_verses', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shloka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.PositiveIntegerField()),
                ('sanskrit', models.TextField()),
                ('transliteration', models.TextField(blank=True)),
                ('english_translation', models.TextField(blank=True)),
                ('hindi_translation', models.TextField(blank=True)),
                ('gujarati_translation', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shlokas', to='gita.chapter')),
            ],
            options={
                'ordering': ['chapter__number', 'verse_number'],
                'constraints': [models.UniqueConstraint(fields=('chapter', 'verse_number'), name='unique_chapter_verse')],
            },
        ),
    ]
