# Generated by Django 6.0.7 on 2026-08-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('language_code', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('translator', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('shloka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gita.shloka')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shloka', 'language_code', 'translator'), name='unique_shloka_translation')],
            },
        ),
    ]
