# Generated by Django 6.0.7 on 2026-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gita', '0002_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shloka',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
