# Generated by Django 6.0.7 on 2026-08-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gita', '0003_shloka_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shloka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insights', to='gita.shloka')),
            ],
        ),
    ]
